
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TaamerProject.Repository.Interfaces;
using TaamerProject.Models.DBContext;
using TaamerProject.Models;
using TaamerProject.Models.Common;

namespace TaamerProject.Repository.Repositories
{
    public class ServicesPricingFormRepository : IServicesPricingFormRepository
    {
        private readonly TaamerProjectContext _TaamerProContext;

        public ServicesPricingFormRepository(TaamerProjectContext dataContext)
        {
            _TaamerProContext = dataContext;

        }

        public async Task<IEnumerable<ServicesPricingFormVM>> GetAllServicesPricingForms(string SearchText, int BranchId)
        {
            if (SearchText == "")
            {
                var Forms = _TaamerProContext.ServicesPricingForm.Where(s => s.IsDeleted == false && s.BranchId==BranchId).Select(x => new ServicesPricingFormVM
                {
                    FormId = x.FormId,
                    Name = x.Name ?? "",
                    Email = x.Email ?? "",
                    Mobile = x.Mobile ?? "",
                    LandArea = x.LandArea ?? "",
                    NumofStreetsAdjacent = x.NumofStreetsAdjacent ?? "",
                    Height = x.Height ?? "",
                    Width = x.Width ?? "",
                    FormType = x.FormType ?? 1,
                    ServiceNotes = x.ServiceNotes ?? "",
                    Bas_swimmingPool = x.Bas_swimmingPool ?? false,
                    Bas_board = x.Bas_board ?? false,
                    Bas_garden = x.Bas_garden ?? false,
                    Bas_LaundryRoom = x.Bas_LaundryRoom ?? false,
                    Bas_storehouse = x.Bas_storehouse ?? false,
                    Bas_carparking = x.Bas_carparking ?? false,
                    Bas_Desk = x.Bas_Desk ?? false,
                    Bas_openkitchen = x.Bas_openkitchen ?? false,
                    Bas_closedkitchen = x.Bas_closedkitchen ?? false,
                    Bas_bedroomonly = x.Bas_bedroomonly ?? false,
                    Bas_Bedandbathroom = x.Bas_Bedandbathroom ?? false,
                    Bas_Healthclub = x.Bas_Healthclub ?? false,
                    Bas_Multipurposehall = x.Bas_Multipurposehall ?? false,
                    Bas_Kidsplayroom = x.Bas_Kidsplayroom ?? false,
                    Bas_Homecinemahall = x.Bas_Homecinemahall ?? false,
                    Bas_Notes = x.Bas_Notes ?? "",
                    Gro_familyliving = x.Gro_familyliving ?? false,
                    Gro_guestdiningroom = x.Gro_guestdiningroom ?? false,
                    Gro_guestcouncil = x.Gro_guestcouncil ?? false,
                    Gro_closedkitchen = x.Gro_closedkitchen ?? false,
                    Gro_Desk = x.Gro_Desk ?? false,
                    Gro_familydiningroom = x.Gro_familydiningroom ?? false,
                    Gro_elevator = x.Gro_elevator ?? false,
                    Gro_Store = x.Gro_Store ?? false,
                    Gro_openkitchen = x.Gro_openkitchen ?? false,
                    Gro_SubEntrance = x.Gro_SubEntrance ?? false,
                    Gro_MainEntrance = x.Gro_MainEntrance ?? false,
                    Gro_Toilets = x.Gro_Toilets ?? false,
                    Gro_Extrabedandbathroom = x.Gro_Extrabedandbathroom ?? false,
                    Gro_servicedrawer = x.Gro_servicedrawer ?? false,
                    Gro_maindrawer = x.Gro_maindrawer ?? false,
                    Gro_Laundryandironingroom = x.Gro_Laundryandironingroom ?? false,
                    Gro_Maidsroomandbathroom = x.Gro_Maidsroomandbathroom ?? false,
                    Gro_Extrabedroomonly = x.Gro_Extrabedroomonly ?? false,
                    Gro_Numberofguestboards = x.Gro_Numberofguestboards ?? "",
                    Gro_Numberoftoilets = x.Gro_Numberoftoilets ?? "",
                    Gro_Notes = x.Gro_Notes ?? "",
                    Firrou_bedroomonly = x.Firrou_bedroomonly ?? false,
                    Firrou_bedandbathroom = x.Firrou_bedandbathroom ?? false,
                    Firrou_Masterbedroomsuite = x.Firrou_Masterbedroomsuite ?? false,
                    Firrou_Smallandopenkitchen = x.Firrou_Smallandopenkitchen ?? false,
                    Firrou_familysitting = x.Firrou_familysitting ?? false,
                    Firrou_WC = x.Firrou_WC ?? false,
                    Firrou_Gym = x.Firrou_Gym ?? false,
                    Firrou_serviceroom = x.Firrou_serviceroom ?? false,
                    Firrou_Desk = x.Firrou_Desk ?? false,
                    Firrou_Numofbednadbathroom = x.Firrou_Numofbednadbathroom ?? "",
                    Firrou_Numofbedroomonly = x.Firrou_Numofbedroomonly ?? "",
                    Firrou_Notes = x.Firrou_Notes ?? "",
                    Sur_storehouse = x.Sur_storehouse ?? false,
                    Sur_WC = x.Sur_WC ?? false,
                    Sur_surface = x.Sur_surface ?? false,
                    Sur_Maidsbedroom = x.Sur_Maidsbedroom ?? false,
                    Sur_Laundryandironingroom = x.Sur_Laundryandironingroom ?? false,
                    Sur_multiusehall = x.Sur_multiusehall ?? false,
                    Sur_Notes = x.Sur_Notes ?? "",
                    Gar_waterbodyonly = x.Gar_waterbodyonly ?? false,
                    Gar_Externalstaircase = x.Gar_Externalstaircase ?? false,
                    Gar_Childrensplayarea = x.Gar_Childrensplayarea ?? false,
                    Gar_outdoorsitting = x.Gar_outdoorsitting ?? false,
                    Gar_swimmingpool = x.Gar_swimmingpool ?? false,
                    Ext_Council = x.Ext_Council ?? false,
                    Ext_Multipurposehall = x.Ext_Multipurposehall ?? false,
                    Ext_WC = x.Ext_WC ?? false,
                    Par_OneCar = x.Par_OneCar ?? false,
                    Par_TwoCar = x.Par_TwoCar ?? false,
                    Par_MoreCars = x.Par_MoreCars ?? false,
                    Par_NoofCars = x.Par_NoofCars ?? "",
                    Dri_OneDriversroomtoilet = x.Dri_OneDriversroomtoilet ?? false,
                    Dri_TwoDriversroomwithtoilets = x.Dri_TwoDriversroomwithtoilets ?? false,
                    Dri_MoreDriversroomwithtoilets = x.Dri_MoreDriversroomwithtoilets ?? false,
                    Dri_NoofDriversroomwithtoilets = x.Dri_NoofDriversroomwithtoilets ?? "",
                    AnotherNotes = x.AnotherNotes ?? "",
                    FormStatus=x.FormStatus??false,
                    URLFile=x.URLFile??"",
                    BranchId=x.BranchId,

                }).ToList();
                return Forms;
            }
            else

            {
                var Forms = _TaamerProContext.ServicesPricingForm.Where(s => s.IsDeleted == false && s.BranchId == BranchId && (s.Name.Contains(SearchText) || s.Email.Contains(SearchText) ||  s.Mobile.Contains(SearchText))).Select(x => new ServicesPricingFormVM
                {
                    FormId = x.FormId,
                    Name = x.Name ?? "",
                    Email = x.Email ?? "",
                    Mobile = x.Mobile ?? "",
                    LandArea = x.LandArea ?? "",
                    NumofStreetsAdjacent = x.NumofStreetsAdjacent ?? "",
                    Height = x.Height ?? "",
                    Width = x.Width ?? "",
                    FormType = x.FormType ?? 1,
                    ServiceNotes = x.ServiceNotes ?? "",
                    Bas_swimmingPool = x.Bas_swimmingPool ?? false,
                    Bas_board = x.Bas_board ?? false,
                    Bas_garden = x.Bas_garden ?? false,
                    Bas_LaundryRoom = x.Bas_LaundryRoom ?? false,
                    Bas_storehouse = x.Bas_storehouse ?? false,
                    Bas_carparking = x.Bas_carparking ?? false,
                    Bas_Desk = x.Bas_Desk ?? false,
                    Bas_openkitchen = x.Bas_openkitchen ?? false,
                    Bas_closedkitchen = x.Bas_closedkitchen ?? false,
                    Bas_bedroomonly = x.Bas_bedroomonly ?? false,
                    Bas_Bedandbathroom = x.Bas_Bedandbathroom ?? false,
                    Bas_Healthclub = x.Bas_Healthclub ?? false,
                    Bas_Multipurposehall = x.Bas_Multipurposehall ?? false,
                    Bas_Kidsplayroom = x.Bas_Kidsplayroom ?? false,
                    Bas_Homecinemahall = x.Bas_Homecinemahall ?? false,
                    Bas_Notes = x.Bas_Notes ?? "",
                    Gro_familyliving = x.Gro_familyliving ?? false,
                    Gro_guestdiningroom = x.Gro_guestdiningroom ?? false,
                    Gro_guestcouncil = x.Gro_guestcouncil ?? false,
                    Gro_closedkitchen = x.Gro_closedkitchen ?? false,
                    Gro_Desk = x.Gro_Desk ?? false,
                    Gro_familydiningroom = x.Gro_familydiningroom ?? false,
                    Gro_elevator = x.Gro_elevator ?? false,
                    Gro_Store = x.Gro_Store ?? false,
                    Gro_openkitchen = x.Gro_openkitchen ?? false,
                    Gro_SubEntrance = x.Gro_SubEntrance ?? false,
                    Gro_MainEntrance = x.Gro_MainEntrance ?? false,
                    Gro_Toilets = x.Gro_Toilets ?? false,
                    Gro_Extrabedandbathroom = x.Gro_Extrabedandbathroom ?? false,
                    Gro_servicedrawer = x.Gro_servicedrawer ?? false,
                    Gro_maindrawer = x.Gro_maindrawer ?? false,
                    Gro_Laundryandironingroom = x.Gro_Laundryandironingroom ?? false,
                    Gro_Maidsroomandbathroom = x.Gro_Maidsroomandbathroom ?? false,
                    Gro_Extrabedroomonly = x.Gro_Extrabedroomonly ?? false,
                    Gro_Numberofguestboards = x.Gro_Numberofguestboards ?? "",
                    Gro_Numberoftoilets = x.Gro_Numberoftoilets ?? "",
                    Gro_Notes = x.Gro_Notes ?? "",
                    Firrou_bedroomonly = x.Firrou_bedroomonly ?? false,
                    Firrou_bedandbathroom = x.Firrou_bedandbathroom ?? false,
                    Firrou_Masterbedroomsuite = x.Firrou_Masterbedroomsuite ?? false,
                    Firrou_Smallandopenkitchen = x.Firrou_Smallandopenkitchen ?? false,
                    Firrou_familysitting = x.Firrou_familysitting ?? false,
                    Firrou_WC = x.Firrou_WC ?? false,
                    Firrou_Gym = x.Firrou_Gym ?? false,
                    Firrou_serviceroom = x.Firrou_serviceroom ?? false,
                    Firrou_Desk = x.Firrou_Desk ?? false,
                    Firrou_Numofbednadbathroom = x.Firrou_Numofbednadbathroom ?? "",
                    Firrou_Numofbedroomonly = x.Firrou_Numofbedroomonly ?? "",
                    Firrou_Notes = x.Firrou_Notes ?? "",
                    Sur_storehouse = x.Sur_storehouse ?? false,
                    Sur_WC = x.Sur_WC ?? false,
                    Sur_surface = x.Sur_surface ?? false,
                    Sur_Maidsbedroom = x.Sur_Maidsbedroom ?? false,
                    Sur_Laundryandironingroom = x.Sur_Laundryandironingroom ?? false,
                    Sur_multiusehall = x.Sur_multiusehall ?? false,
                    Sur_Notes = x.Sur_Notes ?? "",
                    Gar_waterbodyonly = x.Gar_waterbodyonly ?? false,
                    Gar_Externalstaircase = x.Gar_Externalstaircase ?? false,
                    Gar_Childrensplayarea = x.Gar_Childrensplayarea ?? false,
                    Gar_outdoorsitting = x.Gar_outdoorsitting ?? false,
                    Gar_swimmingpool = x.Gar_swimmingpool ?? false,
                    Ext_Council = x.Ext_Council ?? false,
                    Ext_Multipurposehall = x.Ext_Multipurposehall ?? false,
                    Ext_WC = x.Ext_WC ?? false,
                    Par_OneCar = x.Par_OneCar ?? false,
                    Par_TwoCar = x.Par_TwoCar ?? false,
                    Par_MoreCars = x.Par_MoreCars ?? false,
                    Par_NoofCars = x.Par_NoofCars ?? "",
                    Dri_OneDriversroomtoilet = x.Dri_OneDriversroomtoilet ?? false,
                    Dri_TwoDriversroomwithtoilets = x.Dri_TwoDriversroomwithtoilets ?? false,
                    Dri_MoreDriversroomwithtoilets = x.Dri_MoreDriversroomwithtoilets ?? false,
                    Dri_NoofDriversroomwithtoilets = x.Dri_NoofDriversroomwithtoilets ?? "",
                    AnotherNotes = x.AnotherNotes ?? "",
                    FormStatus = x.FormStatus ?? false,
                    URLFile = x.URLFile ?? "",
                    BranchId = x.BranchId,

                }).ToList();
                return Forms;
            }
        }



        public async Task<IEnumerable<ServicesPricingFormVM>> GetAllPublicanddesignServicesPricingForms(int Type, int BranchId)
        {
                var Forms = _TaamerProContext.ServicesPricingForm.Where(s => s.IsDeleted == false && s.BranchId == BranchId && s.FormType==Type ).Select(x => new ServicesPricingFormVM
                {
                    FormId = x.FormId,
                    Name = x.Name ?? "",
                    Email = x.Email ?? "",
                    Mobile = x.Mobile ?? "",
                    LandArea = x.LandArea ?? "",
                    NumofStreetsAdjacent = x.NumofStreetsAdjacent ?? "",
                    Height = x.Height ?? "",
                    Width = x.Width ?? "",
                    FormType = x.FormType ?? 1,
                    ServiceNotes = x.ServiceNotes ?? "",
                    Bas_swimmingPool = x.Bas_swimmingPool ?? false,
                    Bas_board = x.Bas_board ?? false,
                    Bas_garden = x.Bas_garden ?? false,
                    Bas_LaundryRoom = x.Bas_LaundryRoom ?? false,
                    Bas_storehouse = x.Bas_storehouse ?? false,
                    Bas_carparking = x.Bas_carparking ?? false,
                    Bas_Desk = x.Bas_Desk ?? false,
                    Bas_openkitchen = x.Bas_openkitchen ?? false,
                    Bas_closedkitchen = x.Bas_closedkitchen ?? false,
                    Bas_bedroomonly = x.Bas_bedroomonly ?? false,
                    Bas_Bedandbathroom = x.Bas_Bedandbathroom ?? false,
                    Bas_Healthclub = x.Bas_Healthclub ?? false,
                    Bas_Multipurposehall = x.Bas_Multipurposehall ?? false,
                    Bas_Kidsplayroom = x.Bas_Kidsplayroom ?? false,
                    Bas_Homecinemahall = x.Bas_Homecinemahall ?? false,
                    Bas_Notes = x.Bas_Notes ?? "",
                    Gro_familyliving = x.Gro_familyliving ?? false,
                    Gro_guestdiningroom = x.Gro_guestdiningroom ?? false,
                    Gro_guestcouncil = x.Gro_guestcouncil ?? false,
                    Gro_closedkitchen = x.Gro_closedkitchen ?? false,
                    Gro_Desk = x.Gro_Desk ?? false,
                    Gro_familydiningroom = x.Gro_familydiningroom ?? false,
                    Gro_elevator = x.Gro_elevator ?? false,
                    Gro_Store = x.Gro_Store ?? false,
                    Gro_openkitchen = x.Gro_openkitchen ?? false,
                    Gro_SubEntrance = x.Gro_SubEntrance ?? false,
                    Gro_MainEntrance = x.Gro_MainEntrance ?? false,
                    Gro_Toilets = x.Gro_Toilets ?? false,
                    Gro_Extrabedandbathroom = x.Gro_Extrabedandbathroom ?? false,
                    Gro_servicedrawer = x.Gro_servicedrawer ?? false,
                    Gro_maindrawer = x.Gro_maindrawer ?? false,
                    Gro_Laundryandironingroom = x.Gro_Laundryandironingroom ?? false,
                    Gro_Maidsroomandbathroom = x.Gro_Maidsroomandbathroom ?? false,
                    Gro_Extrabedroomonly = x.Gro_Extrabedroomonly ?? false,
                    Gro_Numberofguestboards = x.Gro_Numberofguestboards ?? "",
                    Gro_Numberoftoilets = x.Gro_Numberoftoilets ?? "",
                    Gro_Notes = x.Gro_Notes ?? "",
                    Firrou_bedroomonly = x.Firrou_bedroomonly ?? false,
                    Firrou_bedandbathroom = x.Firrou_bedandbathroom ?? false,
                    Firrou_Masterbedroomsuite = x.Firrou_Masterbedroomsuite ?? false,
                    Firrou_Smallandopenkitchen = x.Firrou_Smallandopenkitchen ?? false,
                    Firrou_familysitting = x.Firrou_familysitting ?? false,
                    Firrou_WC = x.Firrou_WC ?? false,
                    Firrou_Gym = x.Firrou_Gym ?? false,
                    Firrou_serviceroom = x.Firrou_serviceroom ?? false,
                    Firrou_Desk = x.Firrou_Desk ?? false,
                    Firrou_Numofbednadbathroom = x.Firrou_Numofbednadbathroom ?? "",
                    Firrou_Numofbedroomonly = x.Firrou_Numofbedroomonly ?? "",
                    Firrou_Notes = x.Firrou_Notes ?? "",
                    Sur_storehouse = x.Sur_storehouse ?? false,
                    Sur_WC = x.Sur_WC ?? false,
                    Sur_surface = x.Sur_surface ?? false,
                    Sur_Maidsbedroom = x.Sur_Maidsbedroom ?? false,
                    Sur_Laundryandironingroom = x.Sur_Laundryandironingroom ?? false,
                    Sur_multiusehall = x.Sur_multiusehall ?? false,
                    Sur_Notes = x.Sur_Notes ?? "",
                    Gar_waterbodyonly = x.Gar_waterbodyonly ?? false,
                    Gar_Externalstaircase = x.Gar_Externalstaircase ?? false,
                    Gar_Childrensplayarea = x.Gar_Childrensplayarea ?? false,
                    Gar_outdoorsitting = x.Gar_outdoorsitting ?? false,
                    Gar_swimmingpool = x.Gar_swimmingpool ?? false,
                    Ext_Council = x.Ext_Council ?? false,
                    Ext_Multipurposehall = x.Ext_Multipurposehall ?? false,
                    Ext_WC = x.Ext_WC ?? false,
                    Par_OneCar = x.Par_OneCar ?? false,
                    Par_TwoCar = x.Par_TwoCar ?? false,
                    Par_MoreCars = x.Par_MoreCars ?? false,
                    Par_NoofCars = x.Par_NoofCars ?? "",
                    Dri_OneDriversroomtoilet = x.Dri_OneDriversroomtoilet ?? false,
                    Dri_TwoDriversroomwithtoilets = x.Dri_TwoDriversroomwithtoilets ?? false,
                    Dri_MoreDriversroomwithtoilets = x.Dri_MoreDriversroomwithtoilets ?? false,
                    Dri_NoofDriversroomwithtoilets = x.Dri_NoofDriversroomwithtoilets ?? "",
                    AnotherNotes = x.AnotherNotes ?? "",
                    FormStatus = x.FormStatus ?? false,
                    Date = x.ServiceDate??"",
                    URLFile = x.URLFile ?? "",
                    BranchId = x.BranchId,

                }).ToList();
                return Forms;
            }
    



    public async Task<IEnumerable<ServicesPricingFormVM>> GetAllPublicanddesignServicesPricingFormstocount(int Type, int BranchId)
    {
        var Forms = _TaamerProContext.ServicesPricingForm.Where(s => s.IsDeleted == false && s.BranchId == BranchId && s.FormType == Type && s.FormStatus != true).Select(x => new ServicesPricingFormVM
        {
            FormId = x.FormId,
            Name = x.Name ?? "",
            Email = x.Email ?? "",
            Mobile = x.Mobile ?? "",
            LandArea = x.LandArea ?? "",
            NumofStreetsAdjacent = x.NumofStreetsAdjacent ?? "",
            Height = x.Height ?? "",
            Width = x.Width ?? "",
            FormType = x.FormType ?? 1,
            ServiceNotes = x.ServiceNotes ?? "",
            Bas_swimmingPool = x.Bas_swimmingPool ?? false,
            Bas_board = x.Bas_board ?? false,
            Bas_garden = x.Bas_garden ?? false,
            Bas_LaundryRoom = x.Bas_LaundryRoom ?? false,
            Bas_storehouse = x.Bas_storehouse ?? false,
            Bas_carparking = x.Bas_carparking ?? false,
            Bas_Desk = x.Bas_Desk ?? false,
            Bas_openkitchen = x.Bas_openkitchen ?? false,
            Bas_closedkitchen = x.Bas_closedkitchen ?? false,
            Bas_bedroomonly = x.Bas_bedroomonly ?? false,
            Bas_Bedandbathroom = x.Bas_Bedandbathroom ?? false,
            Bas_Healthclub = x.Bas_Healthclub ?? false,
            Bas_Multipurposehall = x.Bas_Multipurposehall ?? false,
            Bas_Kidsplayroom = x.Bas_Kidsplayroom ?? false,
            Bas_Homecinemahall = x.Bas_Homecinemahall ?? false,
            Bas_Notes = x.Bas_Notes ?? "",
            Gro_familyliving = x.Gro_familyliving ?? false,
            Gro_guestdiningroom = x.Gro_guestdiningroom ?? false,
            Gro_guestcouncil = x.Gro_guestcouncil ?? false,
            Gro_closedkitchen = x.Gro_closedkitchen ?? false,
            Gro_Desk = x.Gro_Desk ?? false,
            Gro_familydiningroom = x.Gro_familydiningroom ?? false,
            Gro_elevator = x.Gro_elevator ?? false,
            Gro_Store = x.Gro_Store ?? false,
            Gro_openkitchen = x.Gro_openkitchen ?? false,
            Gro_SubEntrance = x.Gro_SubEntrance ?? false,
            Gro_MainEntrance = x.Gro_MainEntrance ?? false,
            Gro_Toilets = x.Gro_Toilets ?? false,
            Gro_Extrabedandbathroom = x.Gro_Extrabedandbathroom ?? false,
            Gro_servicedrawer = x.Gro_servicedrawer ?? false,
            Gro_maindrawer = x.Gro_maindrawer ?? false,
            Gro_Laundryandironingroom = x.Gro_Laundryandironingroom ?? false,
            Gro_Maidsroomandbathroom = x.Gro_Maidsroomandbathroom ?? false,
            Gro_Extrabedroomonly = x.Gro_Extrabedroomonly ?? false,
            Gro_Numberofguestboards = x.Gro_Numberofguestboards ?? "",
            Gro_Numberoftoilets = x.Gro_Numberoftoilets ?? "",
            Gro_Notes = x.Gro_Notes ?? "",
            Firrou_bedroomonly = x.Firrou_bedroomonly ?? false,
            Firrou_bedandbathroom = x.Firrou_bedandbathroom ?? false,
            Firrou_Masterbedroomsuite = x.Firrou_Masterbedroomsuite ?? false,
            Firrou_Smallandopenkitchen = x.Firrou_Smallandopenkitchen ?? false,
            Firrou_familysitting = x.Firrou_familysitting ?? false,
            Firrou_WC = x.Firrou_WC ?? false,
            Firrou_Gym = x.Firrou_Gym ?? false,
            Firrou_serviceroom = x.Firrou_serviceroom ?? false,
            Firrou_Desk = x.Firrou_Desk ?? false,
            Firrou_Numofbednadbathroom = x.Firrou_Numofbednadbathroom ?? "",
            Firrou_Numofbedroomonly = x.Firrou_Numofbedroomonly ?? "",
            Firrou_Notes = x.Firrou_Notes ?? "",
            Sur_storehouse = x.Sur_storehouse ?? false,
            Sur_WC = x.Sur_WC ?? false,
            Sur_surface = x.Sur_surface ?? false,
            Sur_Maidsbedroom = x.Sur_Maidsbedroom ?? false,
            Sur_Laundryandironingroom = x.Sur_Laundryandironingroom ?? false,
            Sur_multiusehall = x.Sur_multiusehall ?? false,
            Sur_Notes = x.Sur_Notes ?? "",
            Gar_waterbodyonly = x.Gar_waterbodyonly ?? false,
            Gar_Externalstaircase = x.Gar_Externalstaircase ?? false,
            Gar_Childrensplayarea = x.Gar_Childrensplayarea ?? false,
            Gar_outdoorsitting = x.Gar_outdoorsitting ?? false,
            Gar_swimmingpool = x.Gar_swimmingpool ?? false,
            Ext_Council = x.Ext_Council ?? false,
            Ext_Multipurposehall = x.Ext_Multipurposehall ?? false,
            Ext_WC = x.Ext_WC ?? false,
            Par_OneCar = x.Par_OneCar ?? false,
            Par_TwoCar = x.Par_TwoCar ?? false,
            Par_MoreCars = x.Par_MoreCars ?? false,
            Par_NoofCars = x.Par_NoofCars ?? "",
            Dri_OneDriversroomtoilet = x.Dri_OneDriversroomtoilet ?? false,
            Dri_TwoDriversroomwithtoilets = x.Dri_TwoDriversroomwithtoilets ?? false,
            Dri_MoreDriversroomwithtoilets = x.Dri_MoreDriversroomwithtoilets ?? false,
            Dri_NoofDriversroomwithtoilets = x.Dri_NoofDriversroomwithtoilets ?? "",
            AnotherNotes = x.AnotherNotes ?? "",
            FormStatus = x.FormStatus ?? false,
            Date =x.ServiceDate ??"",
            URLFile = x.URLFile ?? "",
            BranchId = x.BranchId,

        }).ToList();
        return Forms;
    }


        public async Task<IEnumerable<ServicesPricingFormVM>> FilterPublicanddesignServicesPricingForms(int Type, int BranchId, string date)
        {
            try {
            var Forms = _TaamerProContext.ServicesPricingForm.Where(s => s.IsDeleted == false && s.BranchId == BranchId && s.FormType == Type).Select(x => new ServicesPricingFormVM
            {
                FormId = x.FormId,
                Name = x.Name ?? "",
                Email = x.Email ?? "",
                Mobile = x.Mobile ?? "",
                LandArea = x.LandArea ?? "",
                NumofStreetsAdjacent = x.NumofStreetsAdjacent ?? "",
                Height = x.Height ?? "",
                Width = x.Width ?? "",
                FormType = x.FormType ?? 1,
                ServiceNotes = x.ServiceNotes ?? "",
                Bas_swimmingPool = x.Bas_swimmingPool ?? false,
                Bas_board = x.Bas_board ?? false,
                Bas_garden = x.Bas_garden ?? false,
                Bas_LaundryRoom = x.Bas_LaundryRoom ?? false,
                Bas_storehouse = x.Bas_storehouse ?? false,
                Bas_carparking = x.Bas_carparking ?? false,
                Bas_Desk = x.Bas_Desk ?? false,
                Bas_openkitchen = x.Bas_openkitchen ?? false,
                Bas_closedkitchen = x.Bas_closedkitchen ?? false,
                Bas_bedroomonly = x.Bas_bedroomonly ?? false,
                Bas_Bedandbathroom = x.Bas_Bedandbathroom ?? false,
                Bas_Healthclub = x.Bas_Healthclub ?? false,
                Bas_Multipurposehall = x.Bas_Multipurposehall ?? false,
                Bas_Kidsplayroom = x.Bas_Kidsplayroom ?? false,
                Bas_Homecinemahall = x.Bas_Homecinemahall ?? false,
                Bas_Notes = x.Bas_Notes ?? "",
                Gro_familyliving = x.Gro_familyliving ?? false,
                Gro_guestdiningroom = x.Gro_guestdiningroom ?? false,
                Gro_guestcouncil = x.Gro_guestcouncil ?? false,
                Gro_closedkitchen = x.Gro_closedkitchen ?? false,
                Gro_Desk = x.Gro_Desk ?? false,
                Gro_familydiningroom = x.Gro_familydiningroom ?? false,
                Gro_elevator = x.Gro_elevator ?? false,
                Gro_Store = x.Gro_Store ?? false,
                Gro_openkitchen = x.Gro_openkitchen ?? false,
                Gro_SubEntrance = x.Gro_SubEntrance ?? false,
                Gro_MainEntrance = x.Gro_MainEntrance ?? false,
                Gro_Toilets = x.Gro_Toilets ?? false,
                Gro_Extrabedandbathroom = x.Gro_Extrabedandbathroom ?? false,
                Gro_servicedrawer = x.Gro_servicedrawer ?? false,
                Gro_maindrawer = x.Gro_maindrawer ?? false,
                Gro_Laundryandironingroom = x.Gro_Laundryandironingroom ?? false,
                Gro_Maidsroomandbathroom = x.Gro_Maidsroomandbathroom ?? false,
                Gro_Extrabedroomonly = x.Gro_Extrabedroomonly ?? false,
                Gro_Numberofguestboards = x.Gro_Numberofguestboards ?? "",
                Gro_Numberoftoilets = x.Gro_Numberoftoilets ?? "",
                Gro_Notes = x.Gro_Notes ?? "",
                Firrou_bedroomonly = x.Firrou_bedroomonly ?? false,
                Firrou_bedandbathroom = x.Firrou_bedandbathroom ?? false,
                Firrou_Masterbedroomsuite = x.Firrou_Masterbedroomsuite ?? false,
                Firrou_Smallandopenkitchen = x.Firrou_Smallandopenkitchen ?? false,
                Firrou_familysitting = x.Firrou_familysitting ?? false,
                Firrou_WC = x.Firrou_WC ?? false,
                Firrou_Gym = x.Firrou_Gym ?? false,
                Firrou_serviceroom = x.Firrou_serviceroom ?? false,
                Firrou_Desk = x.Firrou_Desk ?? false,
                Firrou_Numofbednadbathroom = x.Firrou_Numofbednadbathroom ?? "",
                Firrou_Numofbedroomonly = x.Firrou_Numofbedroomonly ?? "",
                Firrou_Notes = x.Firrou_Notes ?? "",
                Sur_storehouse = x.Sur_storehouse ?? false,
                Sur_WC = x.Sur_WC ?? false,
                Sur_surface = x.Sur_surface ?? false,
                Sur_Maidsbedroom = x.Sur_Maidsbedroom ?? false,
                Sur_Laundryandironingroom = x.Sur_Laundryandironingroom ?? false,
                Sur_multiusehall = x.Sur_multiusehall ?? false,
                Sur_Notes = x.Sur_Notes ?? "",
                Gar_waterbodyonly = x.Gar_waterbodyonly ?? false,
                Gar_Externalstaircase = x.Gar_Externalstaircase ?? false,
                Gar_Childrensplayarea = x.Gar_Childrensplayarea ?? false,
                Gar_outdoorsitting = x.Gar_outdoorsitting ?? false,
                Gar_swimmingpool = x.Gar_swimmingpool ?? false,
                Ext_Council = x.Ext_Council ?? false,
                Ext_Multipurposehall = x.Ext_Multipurposehall ?? false,
                Ext_WC = x.Ext_WC ?? false,
                Par_OneCar = x.Par_OneCar ?? false,
                Par_TwoCar = x.Par_TwoCar ?? false,
                Par_MoreCars = x.Par_MoreCars ?? false,
                Par_NoofCars = x.Par_NoofCars ?? "",
                Dri_OneDriversroomtoilet = x.Dri_OneDriversroomtoilet ?? false,
                Dri_TwoDriversroomwithtoilets = x.Dri_TwoDriversroomwithtoilets ?? false,
                Dri_MoreDriversroomwithtoilets = x.Dri_MoreDriversroomwithtoilets ?? false,
                Dri_NoofDriversroomwithtoilets = x.Dri_NoofDriversroomwithtoilets ?? "",
                AnotherNotes = x.AnotherNotes ?? "",
                FormStatus = x.FormStatus ?? false,
                Date = x.ServiceDate ?? "",
                URLFile = x.URLFile ?? "",
                BranchId = x.BranchId,

            }).ToList().Where(s => DateTime.ParseExact(s.Date, "yyyy-MM-dd", CultureInfo.InvariantCulture) <= DateTime.ParseExact(DateTime.Now.ToString("yyyy-MM-dd", CultureInfo.CreateSpecificCulture("en")), "yyyy-MM-dd", CultureInfo.InvariantCulture) &&
            DateTime.ParseExact(s.Date, "yyyy-MM-dd", CultureInfo.InvariantCulture) >= DateTime.ParseExact(date, "yyyy-MM-dd", CultureInfo.InvariantCulture));
            return Forms;
            }
            catch (Exception ex)
            {
                IEnumerable<ServicesPricingFormVM> form = new List<ServicesPricingFormVM>();
                return form;
            }
        }
        public async Task<ServicesPricingFormVM> GetServicesPricingFormById(int FormId, int BranchId)
        {
            var Forms = _TaamerProContext.ServicesPricingForm.Where(s => s.IsDeleted == false && s.FormId==FormId).Select(x => new ServicesPricingFormVM
            {
                FormId = x.FormId,
                Name = x.Name ?? "",
                Email = x.Email ?? "",
                Mobile = x.Mobile ?? "",
                LandArea = x.LandArea ?? "",
                NumofStreetsAdjacent = x.NumofStreetsAdjacent ?? "",
                Height = x.Height ?? "",
                Width = x.Width ?? "",
                FormType = x.FormType ?? 1,
                ServiceNotes = x.ServiceNotes ?? "",
                Bas_swimmingPool = x.Bas_swimmingPool ?? false,
                Bas_board = x.Bas_board ?? false,
                Bas_garden = x.Bas_garden ?? false,
                Bas_LaundryRoom = x.Bas_LaundryRoom ?? false,
                Bas_storehouse = x.Bas_storehouse ?? false,
                Bas_carparking = x.Bas_carparking ?? false,
                Bas_Desk = x.Bas_Desk ?? false,
                Bas_openkitchen = x.Bas_openkitchen ?? false,
                Bas_closedkitchen = x.Bas_closedkitchen ?? false,
                Bas_bedroomonly = x.Bas_bedroomonly ?? false,
                Bas_Bedandbathroom = x.Bas_Bedandbathroom ?? false,
                Bas_Healthclub = x.Bas_Healthclub ?? false,
                Bas_Multipurposehall = x.Bas_Multipurposehall ?? false,
                Bas_Kidsplayroom = x.Bas_Kidsplayroom ?? false,
                Bas_Homecinemahall = x.Bas_Homecinemahall ?? false,
                Bas_Notes = x.Bas_Notes ?? "",
                Gro_familyliving = x.Gro_familyliving ?? false,
                Gro_guestdiningroom = x.Gro_guestdiningroom ?? false,
                Gro_guestcouncil = x.Gro_guestcouncil ?? false,
                Gro_closedkitchen = x.Gro_closedkitchen ?? false,
                Gro_Desk = x.Gro_Desk ?? false,
                Gro_familydiningroom = x.Gro_familydiningroom ?? false,
                Gro_elevator = x.Gro_elevator ?? false,
                Gro_Store = x.Gro_Store ?? false,
                Gro_openkitchen = x.Gro_openkitchen ?? false,
                Gro_SubEntrance = x.Gro_SubEntrance ?? false,
                Gro_MainEntrance = x.Gro_MainEntrance ?? false,
                Gro_Toilets = x.Gro_Toilets ?? false,
                Gro_Extrabedandbathroom = x.Gro_Extrabedandbathroom ?? false,
                Gro_servicedrawer = x.Gro_servicedrawer ?? false,
                Gro_maindrawer = x.Gro_maindrawer ?? false,
                Gro_Laundryandironingroom = x.Gro_Laundryandironingroom ?? false,
                Gro_Maidsroomandbathroom = x.Gro_Maidsroomandbathroom ?? false,
                Gro_Extrabedroomonly = x.Gro_Extrabedroomonly ?? false,
                Gro_Numberofguestboards = x.Gro_Numberofguestboards ?? "",
                Gro_Numberoftoilets = x.Gro_Numberoftoilets ?? "",
                Gro_Notes = x.Gro_Notes ?? "",
                Firrou_bedroomonly = x.Firrou_bedroomonly ?? false,
                Firrou_bedandbathroom = x.Firrou_bedandbathroom ?? false,
                Firrou_Masterbedroomsuite = x.Firrou_Masterbedroomsuite ?? false,
                Firrou_Smallandopenkitchen = x.Firrou_Smallandopenkitchen ?? false,
                Firrou_familysitting = x.Firrou_familysitting ?? false,
                Firrou_WC = x.Firrou_WC ?? false,
                Firrou_Gym = x.Firrou_Gym ?? false,
                Firrou_serviceroom = x.Firrou_serviceroom ?? false,
                Firrou_Desk = x.Firrou_Desk ?? false,
                Firrou_Numofbednadbathroom = x.Firrou_Numofbednadbathroom ?? "",
                Firrou_Numofbedroomonly = x.Firrou_Numofbedroomonly ?? "",
                Firrou_Notes = x.Firrou_Notes ?? "",
                Sur_storehouse = x.Sur_storehouse ?? false,
                Sur_WC = x.Sur_WC ?? false,
                Sur_surface = x.Sur_surface ?? false,
                Sur_Maidsbedroom = x.Sur_Maidsbedroom ?? false,
                Sur_Laundryandironingroom = x.Sur_Laundryandironingroom ?? false,
                Sur_multiusehall = x.Sur_multiusehall ?? false,
                Sur_Notes = x.Sur_Notes ?? "",
                Gar_waterbodyonly = x.Gar_waterbodyonly ?? false,
                Gar_Externalstaircase = x.Gar_Externalstaircase ?? false,
                Gar_Childrensplayarea = x.Gar_Childrensplayarea ?? false,
                Gar_outdoorsitting = x.Gar_outdoorsitting ?? false,
                Gar_swimmingpool = x.Gar_swimmingpool ?? false,
                Ext_Council = x.Ext_Council ?? false,
                Ext_Multipurposehall = x.Ext_Multipurposehall ?? false,
                Ext_WC = x.Ext_WC ?? false,
                Par_OneCar = x.Par_OneCar ?? false,
                Par_TwoCar = x.Par_TwoCar ?? false,
                Par_MoreCars = x.Par_MoreCars ?? false,
                Par_NoofCars = x.Par_NoofCars ?? "",
                Dri_OneDriversroomtoilet = x.Dri_OneDriversroomtoilet ?? false,
                Dri_TwoDriversroomwithtoilets = x.Dri_TwoDriversroomwithtoilets ?? false,
                Dri_MoreDriversroomwithtoilets = x.Dri_MoreDriversroomwithtoilets ?? false,
                Dri_NoofDriversroomwithtoilets = x.Dri_NoofDriversroomwithtoilets ?? "",
                AnotherNotes = x.AnotherNotes ?? "",
                FormStatus = x.FormStatus ?? false,
                URLFile = x.URLFile ?? "",
                Date = x.ServiceDate ?? "",
                BranchId = x.BranchId,

            }).FirstOrDefault();
            return Forms;

        }

    }
}
